# Generated by Django 4.1.3 on 2022-11-30 22:03

from django.db import migrations, models
import online_supermarket_api.const


class Migration(migrations.Migration):

    dependencies = [
        ('online_supermarket_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selling',
            name='status',
            field=models.CharField(blank=True, default=online_supermarket_api.const.SellingStatus['PENDING'], max_length=16, null=True),
        ),
    ]
