# Generated by Django 4.1.2 on 2022-10-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('image_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Selling',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('status', models.CharField(max_length=16)),
                ('created_date', models.DateField()),
                ('canceled_date', models.DateField()),
                ('delivered_date', models.DateField()),
            ],
            options={
                'db_table': 'selling',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SellingProduct',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('selling_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'selling_product',
                'managed': False,
            },
        ),
    ]
