# Generated by Django 4.1.2 on 2022-10-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_supermarket_api', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selling',
            name='canceled_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='selling',
            name='delivered_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='selling',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
    ]
