# Generated by Django 4.1.3 on 2022-12-04 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_supermarket_api', '0003_alter_selling_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellingproduct',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='sellingproduct',
            old_name='selling_id',
            new_name='selling',
        ),
    ]
