# Generated by Django 4.1.3 on 2022-12-15 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online_supermarket_api', '0004_rename_product_id_sellingproduct_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selling',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
