# Generated by Django 4.1.3 on 2022-12-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_supermarket_api', '0002_alter_selling_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selling',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=16, null=True),
        ),
    ]
